### ISSUE TITLE
'GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by daugustus** [xaberus/vscode-remote-oss#10]
Latest update today on Vscodium to latest version:
Version: 1.85.0
Release: 23343
Commit: 00c993f9b9a2a07730235274df02f05bd76575f7
Date: 2023-12-09T18:17:56.779Z (3 days ago)
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

Remote host: AlmaLinux release 8.8 (Sapphire Caracal)

Running server after downloading latest version results in this error on remote:
- Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

Not sure if there a workaround for almalinux 8. Does this latest version now require version 9 ?

**Comment by xaberus** [comment]
This seems to be an incompatibility with the REH package provided by VSCodium. I am not quite sure what container is used to build the package, but the runtime inherits (among other things) the `glibc` dependency of the build environment. You can try contacting the VSCodium maintainers about the details. If worse comes to worst, you can build the REH yourself in the environment you intent it to run...
