### ISSUE TITLE
Unable to connect with `File: Open Recent` command if the remote label contains uppercase letters

### ISSUE THREAD

**Issue by nnn1590** [xaberus/vscode-remote-oss#11]
If remote label(`name`) contains uppercase letters:
```jsonc
// setting.json

    "remote.OSS.hosts": [
        {
            "type": "manual",
            "name": "WSL2 Ubuntu-22.04",
            "host": "localhost",
            "port": 8000,
            "connectionToken": "<TOKEN>"
        }
    ],
```
opening the remote folder from `File: Open Recent...` or recent list on the welcome page fails with `Host <remote label in lowercase>
is not available.`
![Welcome page on VSCode and selecting the "File: Open Recent..." command](https://github.com/xaberus/vscode-remote-oss/assets/28985763/b6209f6f-9bc0-43cb-99d3-133fa0c8164d)
![The editor displays "The editor could not be opened due to an unexpected error: ENOPRO: No file system provider found for resource 'vscode-remote://remote-oss%2Bwsl2%20ubuntu-22.04/tmp/tmp/Untitled-1'" and the console in developher tools shows "CodeExpectedError: Host wsl2 ubuntu-22.04 is not available."](https://github.com/xaberus/vscode-remote-oss/assets/28985763/dc7b9123-5cfa-40d8-9c29-d0e3705b41e9)

The problem does not occur if you connect to the remote with `Remote-OSS: Connect Current Window to Host...` and then open the folder with `File: Open Folder... (Ctrl+K Ctrl+O)` or convert the label to lower case.

remote-oss: v0.0.3
VSCodium:
> Version: 1.89.0
> Release: 24127
> Commit: 4379b66f0d4dd9881ba96fa086f387725b69a24b
> Date: 2024-05-06T18:01:39.568Z
> Electron: 28.2.8
> ElectronBuildId: undefined
> Chromium: 120.0.6099.291
> Node.js: 18.18.2
> V8: 12.0.267.19-electron.0
> OS: Windows_NT x64 10.0.22621

remote server: [vscodium-reh-linux-x64-1.89.0.24127](https://github.com/VSCodium/vscodium/releases/download/1.89.0.24127/vscodium-reh-linux-x64-1.89.0.24127.tar.gz) on Ubuntu 22.04 LTS amd64 on WSL2

**Comment by xaberus** [comment]
Hi, this is a very strange issue. Basically the label's case does not survive a round trip through the URI parser. Is there any better was than to encode the label in a hex string? (Base64 for example does not work, because it is also case sensitive.)

My proposed solution (hex encoding the label) is for example:
```yaml
label: "Bee reh-8000"
```
will turn into
```yaml
authority: "remote-oss+426565207265682d38303030"
```
where the part after `remote-oss+` is the hex-encoded label.

This [patch](https://github.com/xaberus/vscode-remote-oss/pull/12) would work, but feels quite ugly. I hope this makes sense... @nnn1590 can you try out the patch to check if I missed something before I release it?

**Comment by nnn1590** [comment]
Thank you, but it didn't work.

Output view shows:
* If I start a new connection: `resolving authority: remote-oss+<remote label>`
* if I connect from a recently opened folder: `resolving authority: remote-oss+<remote label in lowercase>`

so it appears that `resolve()` is receiving an unencoded authority.
https://github.com/xaberus/vscode-remote-oss/blob/fc90ce3011aac21adc13be9fd2bebe36ead6aba1/src/extension.ts#L54-L56

![The output view of VSCodium and dev tools. output view shows "resolving authority: remote-oss+WSL2 Ubuntu-22.04
" and dev tools shows "ERR [LocalProcess0][resolveAuthority(remote-oss,1)][362ms] returned an error {code: 'NotAvailable', message: 'Invalid', detail: true}"](https://github.com/xaberus/vscode-remote-oss/assets/28985763/530b0ac0-2c95-40c2-a748-cd5e0ed46a56)

**Comment by xaberus** [comment]
Hm, did you clear the recent entry list? I had to clear the list as the old entries have not been encoded. Can you retry with a clean recent list, please?

**Comment by nnn1590** [comment]
I tried again after clearing the recent list. Also, I tried it on a different physical Ubuntu 20.04 machine that had never connected to the remote in the past. But I got same reuslt.

However, when I duplicated host and encoded `name`, it worked!
```jsonc
    "remote.OSS.hosts": [
        {
            "type": "manual",
            "name": "WSL2 Ubuntu-22.04",
            "host": "localhost",
            "port": 8000,
            "connectionToken": "<TOKEN>"
        },
        {
            "type": "manual",
            "name": "57534c32205562756e74752d32322e3034",  // `WSL2 Ubuntu-22.04` in hex
            "host": "localhost",
            "port": 8000,
            "connectionToken": "<TOKEN>"
        }
    ]

```

**Comment by nnn1590** [comment]
How about making the label case-insensitive?
```diff
diff --git a/src/remotesView.ts b/src/remotesView.ts
index 84971b3..2802bd0 100644
--- a/src/remotesView.ts
+++ b/src/remotesView.ts
@@ -230,7 +230,7 @@ export class RemotesDataProvider implements TreeDataProvider<TreeItem>{
     ): Promise<ResolvedAuthority> {
         channel.append(`connecting to ${label}...`);
 
-        const hosts = (await this.getHostList()).filter(h => h.label === label);
+        const hosts = (await this.getHostList()).filter(h => typeof h.label === "string" && h.label.toLowerCase() === label.toLowerCase());
         if (!hosts || hosts.length === 0) {
             throw RemoteAuthorityResolverError.NotAvailable(`Host ${label} is not available.`, true);
         }

```
this patch is based on v0.0.3

**Comment by xaberus** [comment]
@nnn1590 I do not want to just ignore the case here, as this round-trip failure is an oversight from my side that potentially could also break for other characters that do not have a normal form. The hex encoding should solve that. What I am not getting is why it is not working for you. Did you test the extension in the **debug mode** or did you compile (`npm run package`) and install the VSIX? I just noticed that in the former case the recent entries list is not updated on my machine - only if VSCodium is run in **normal mode**.

**Comment by nnn1590** [comment]
I compiled vsix(`npx vsce package`) and install it in normal mode VSCodium.

**Comment by xaberus** [comment]
Darn, I forgot to encode the picker result... and let me guess, you connect to the remote host through the command palette and not through the remote view? I am so sorry... Can you please test the new patch?

**Comment by nnn1590** [comment]
> you connect to the remote host through the command palette and not through the remote view?

Yes! I'm sorry for not being able to explain well how I connect.

The new patch works well for me 😁 Thank you so much!

**Comment by xaberus** [comment]
@nnn1590 I revisited the patch to make the transition hopefully less random. Can you please test if this works as intended? This should raise a warning when a "legacy" un-encoded uri is opened from the recent list to remind the users to clear it... Thanks!

**Comment by nnn1590** [comment]
Revisited patch works well! 😊👍
